### Creating a user
POST http://localhost:1234/signup
Content-Type: application/json

{
    "username": "user",
    "email": "test@test.com",
    "password": "password",
    "confirmPassword": "password"
}

### login a user
POST http://localhost:1234/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}